tests: skip importstd with gcc on Windows
It's failing since we updated from gcc 15.2 to 16.1 in MSYS2.

The test was checking for an unreleased 15.3 so the test was never
run on Windows to begin with. Just skip it with gcc on Windows.

fyi, it fails with:
undefined reference to `std::__open_terminal(_iobuf*)'
undefined reference to `std::__write_to_terminal(void*, std::span<char, 4294967295u>)'